name: Daily Sim (Gemini)

on:
  workflow_dispatch: {}
  schedule:
    # Run every 30 minutes during US market hours in UTC
    # 14:30-20:00 UTC = 09:30-15:00 ET (winter)
    - cron: '*/30 14-20 * * 1-5'

permissions:
  contents: write

concurrency:
  group: sim-artifacts
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . google-generativeai matplotlib

      - name: Run Gemini competitor
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python -m src.runner_gemini --universe sp500 --max-symbols 500 --interval 5m --period 5d --max-positions 20

      - name: Render Gemini equity chart
        run: |
          python -m pip install matplotlib || true
          python -m src.tools.plot_equity --equity artifacts_gemini/equity.jsonl --out artifacts_gemini/equity.png || true

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f artifacts_gemini/equity.jsonl 2>/dev/null || true
          git add -f artifacts_gemini/equity.png 2>/dev/null || true
          git add -f artifacts_gemini/trades.jsonl 2>/dev/null || true
          git add -f artifacts_gemini/decisions.jsonl 2>/dev/null || true
          # cache-bust README image links by appending a short token
          SHA=$(git rev-parse --short HEAD || date +%s)
          perl -0777 -pe "s|(artifacts/equity.png)(\?v=[0-9a-f]+)?|\1?v=${SHA}|g; s|(artifacts_gemini/equity.png)(\?v=[0-9a-f]+)?|\1?v=${SHA}|g" -i README.md || true
          git add README.md || true
          if git diff --cached --quiet; then
            echo "No changes"; exit 0; fi
          git commit -m "chore(gemini): update equity/trades/decisions [skip ci]"
          # rebase to avoid push rejects when other workflow updated main
          git fetch origin
          git pull --rebase --autostash origin main || true
          git push